create type public.event_type as enum ('webinar', 'workshop', 'seminar', 'training');
create type public.delivery_method as enum ('online', 'face_to_face', 'hybrid');

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title varchar not null,
  description text,
  type public.event_type not null default 'webinar',
  delivery public.delivery_method not null default 'online',
  event_date date not null,
  start_time time,
  end_time time,
  quota integer default 0,
  price integer default 0,
  thumbnail_url text,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  title varchar not null,
  slug varchar not null unique,
  description text,
  benefits text,
  image_1_url text,
  image_2_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.trainers (
  id bigint generated by default as identity primary key,
  name varchar not null,
  role_title varchar default 'Trainer .id Academy',
  photo_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  title varchar not null,
  description text,
  link_url text,
  thumbnail_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.events enable row level security;
alter table public.programs enable row level security;
alter table public.trainers enable row level security;
alter table public.materials enable row level security;

create policy "Public can read published events"
  on public.events for select
  using (is_published = true);

create policy "Public can read active programs"
  on public.programs for select
  using (is_active = true);

create policy "Public can read active trainers"
  on public.trainers for select
  using (is_active = true);

create policy "Public can read active materials"
  on public.materials for select
  using (is_active = true);

-- For admin CRUD from the current dashboard client, add authenticated/admin-specific
-- insert/update/delete policies that fit your Supabase Auth setup before production.
